import V from"./B-mooT-D.js";import{multiTabVariants as W}from"./4izIKCHV.js";import{N as M,bE as U,as as y,aD as A,aI as D,v as T,w as O,F as _,aX as q,au as b,bk as a,c9 as h,aY as z,I as J,bb as X,aw as Y,J as E,aU as r,s as j,aL as $}from"./DWvl5oxm.js";const G=["onClick"],Q=M({__name:"List",props:{variant:{},tabs:{},activeTab:{},classes:{}},emits:["update:activeTab"],setup(n,{emit:B}){const c=n,F=B,s=r(null),x=r(new Map),u=r(null),m=r(null),w=r(null),p=r(!1),g=r(!1),v=j(()=>W({variant:c.variant})),I=(e,l)=>{l&&x.value.set(e,l)},N=e=>{F("update:activeTab",e)},f=()=>{if(!s.value){p.value=!1,g.value=!1;return}const e=s.value,l=e.scrollLeft,o=e.scrollWidth,t=e.clientWidth;p.value=l>1,g.value=l+t<o-1},d=(e=!1)=>{if(!c.activeTab){u.value=null;return}const l=x.value.get(c.activeTab),o=s.value;if(!l||!o){u.value=null;return}const t=o.getBoundingClientRect(),i=l.getBoundingClientRect(),R=i.left-t.left+o.scrollLeft,S=i.top-t.top,C=e?"transition: none;":"";c.variant==="underline"?u.value=`
      left: ${R}px;
      width: ${i.width}px;
      ${C}
      `:u.value=`
          left: ${R}px;
          top: ${S}px;
          width: ${i.width}px;
          height: ${i.height}px;
          ${C}
        `};let k=!1,L=!0;return U(()=>c.activeTab,()=>{k=!0,y(()=>{d(L),L=!1,requestAnimationFrame(()=>{k=!1})})},{immediate:!0}),A(()=>{y(()=>{f(),d(!0)}),m.value=new ResizeObserver(()=>{f(),d(!0)}),w.value=new MutationObserver(()=>{k||y(()=>{d(!0),f()})}),s.value&&(m.value.observe(s.value),s.value.addEventListener("scroll",f),w.value.observe(s.value,{attributes:!0,childList:!0,subtree:!0,attributeFilter:["style","class"]}))}),D(()=>{m.value?.disconnect(),w.value?.disconnect(),s.value&&s.value.removeEventListener("scroll",f)}),(e,l)=>{const o=V;return $(),T("div",{class:b(a(h)(a(v).root(),n.classes?.root))},[O("ul",{ref_key:"listRef",ref:s,class:b(a(h)(a(v).list(),n.classes?.list))},[($(!0),T(_,null,q(n.tabs,t=>($(),T("li",{key:t.key,ref_for:!0,ref:i=>I(t.key,i),class:b(a(h)(a(v).tab(),n.classes?.tab,n.activeTab===t.key&&[a(v).active(),n.classes?.active])),onClick:i=>N(t.key)},[z(e.$slots,`tab-content-prefix-${t.key}`),J(" "+X(t.title)+" ",1),z(e.$slots,`tab-content-suffix-${t.key}`)],10,G))),128)),O("div",{class:b(a(h)(a(v).indicator(),n.classes?.indicator)),style:Y(a(u))},null,6)],2),E(o,{show:a(p),class:"absolute z-30 top-0 left-0 w-3.5 h-full bg-gradient-to-r from-white to-transparent md:w-7"},null,8,["show"]),E(o,{show:a(g),class:"absolute z-30 top-0 right-0 w-3.5 h-full bg-gradient-to-l from-white to-transparent md:w-7"},null,8,["show"])],2)}}});export{Q as _};
